version: '3.8'

services:
  backend:
    build: ./flask-app
    container_name: backend
    ports:
      - "5000:5000"

  frontend:
    build: ./react
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

